### ISSUE TITLE
Using own mysql server

### ISSUE THREAD

**Issue by bitdegree67** [ONLYOFFICE/Docker-DocumentServer#122]
Can we use own mysql server with this image ?

**Comment by ShockwaveNN** [comment]
https://github.com/ONLYOFFICE/Docker-DocumentServer#available-configuration-parameters
`POSTGRESQL_SERVER_HOST` and etc

**Comment by markuman** [comment]
@ShockwaveNN So I can pass a **mysql** (or mariadb) host as **POSTGRES**QL_SERVER_HOST? And that works? I mean, postgres and mysql has different protocols ...  
same mentioned here  https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/5#issuecomment-392675647

**Comment by markuman** [comment]
I expect an env Variable for `DATABASE_SERVER_TYPE` (mysql or postgres) and generic names 

`DATABASE_SERVER_HOST` instead of `POSTGRESQL_SERVER_HOST`

**Comment by markuman** [comment]
https://github.com/ONLYOFFICE/DocumentServer/blob/dd43575e3090131153e10cce3c0a1ead94e9919c/CHANGELOG.md#back-end-31

> Use PostgreSQL instead of MySQL on back-end

Or is the mysql backend dropped since 4.1.2?

**Comment by ShockwaveNN** [comment]
> Or is the mysql backend dropped since 4.1.2?

No, it's changelog entry about default DB in Docker Image

> So I can pass a mysql (or mariadb) host as POSTGRESQL_SERVER_HOST

Not sure about mariadb, but mysql should work

**Comment by markuman** [comment]
> Not sure about mariadb, but mysql should work

it doesn't seems to work, because `psql` is not able to talk to a mysql nor a mariadb server. The mariadb is running in the `db` network.

```
docker run -ti --rm  --name office -e JWT_ENABLED='true' -e JWT_SECRET='sometoken' --network db -e POSTGRESQL_SERVER_HOST=mariadb -e POSTGRESQL_SERVER_PORT=3306 -e POSTGRESQL_SERVER_DB_NAME=onlyoffice -e POSTGRESQL_SERVER_USER=onlyoffice -e POSTGRESQL_SERVER_PASS=onlyoffice onlyoffice/documentserver
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
psql: received invalid response to SSL negotiation: ]
psql: received invalid response to SSL negotiation: ]
```

mysql cli is also not installed

```
root@54b84e9bed31:/# ps
ps       psql     pstruct  
root@54b84e9bed31:/# ps
ps       psql     pstruct  
root@54b84e9bed31:/# my
```

The startup script is considering only postgres https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/run-document-server.sh#L244

When patching the dockerfile like this 

```Dockerfile
FROM onlyoffice/documentserver

RUN sed -i 's/postgres/mysql/' /etc/onlyoffice/documentserver/default.json
```

it results in

```
office.1.p48z15k2u418@hetzner    | [2019-10-07T07:46:01.951] [ERROR] nodeJS - { Error: ER_NO_SUCH_TABLE: Table 'onlyoffice.task_result' doesn't exist
office.1.p48z15k2u418@hetzner    |     at Query.Sequence._packetToError (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
office.1.p48z15k2u418@hetzner    |     at Query.ErrorPacket (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
office.1.p48z15k2u418@hetzner    |     at Protocol._parsePacket (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:291:23)
office.1.p48z15k2u418@hetzner    |     at Parser._parsePacket (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Parser.js:433:10)
office.1.p48z15k2u418@hetzner    |     at Parser.write (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Parser.js:43:10)
office.1.p48z15k2u418@hetzner    |     at Protocol.write (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:38:16)
office.1.p48z15k2u418@hetzner    |     at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:91:28)
office.1.p48z15k2u418@hetzner    |     at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:525:10)
office.1.p48z15k2u418@hetzner    |     at emitOne (events.js:116:13)
office.1.p48z15k2u418@hetzner    |     at Socket.emit (events.js:211:7)
office.1.p48z15k2u418@hetzner    |     at addChunk (_stream_readable.js:263:12)
office.1.p48z15k2u418@hetzner    |     at readableAddChunk (_stream_readable.js:250:11)
office.1.p48z15k2u418@hetzner    |     at Socket.Readable.push (_stream_readable.js:208:10)
office.1.p48z15k2u418@hetzner    |     at TCP.onread (net.js:601:20)
office.1.p48z15k2u418@hetzner    |     --------------------
office.1.p48z15k2u418@hetzner    |     at Protocol._enqueue (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:144:48)
office.1.p48z15k2u418@hetzner    |     at PoolConnection.query (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:201:25)
office.1.p48z15k2u418@hetzner    |     at /var/www/onlyoffice/documentserver/server/DocService/sources/mySqlBaseConnector.js:36:14
office.1.p48z15k2u418@hetzner    |     at Handshake.onConnect (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Pool.js:64:7)
office.1.p48z15k2u418@hetzner    |     at Handshake.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:525:10)
office.1.p48z15k2u418@hetzner    |     at Handshake._callback (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:491:16)
office.1.p48z15k2u418@hetzner    |     at Handshake.Sequence.end (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
office.1.p48z15k2u418@hetzner    |     at Handshake.Sequence.OkPacket (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
office.1.p48z15k2u418@hetzner    |     at Protocol._parsePacket (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:291:23)
office.1.p48z15k2u418@hetzner    |     at Parser._parsePacket (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Parser.js:433:10)
office.1.p48z15k2u418@hetzner    |     at Parser.write (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Parser.js:43:10)
office.1.p48z15k2u418@hetzner    |     at Protocol.write (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:38:16)
office.1.p48z15k2u418@hetzner    |     at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:91:28)
office.1.p48z15k2u418@hetzner    |     at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:525:10)
office.1.p48z15k2u418@hetzner    |     at emitOne (events.js:116:13)
office.1.p48z15k2u418@hetzner    |     at Socket.emit (events.js:211:7)
office.1.p48z15k2u418@hetzner    |   code: 'ER_NO_SUCH_TABLE',
office.1.p48z15k2u418@hetzner    |   errno: 1146,
office.1.p48z15k2u418@hetzner    |   sqlMessage: 'Table \'onlyoffice.task_result\' doesn\'t exist',
office.1.p48z15k2u418@hetzner    |   sqlState: '42S02',
office.1.p48z15k2u418@hetzner    |   index: 0,
office.1.p48z15k2u418@hetzner    |   sql: 'INSERT INTO task_result ( id, status, status_info, last_open_date, user_index, change_id, callback, baseurl ) VALUES (\'3421633105\', 0, 0, \'2019-10-07 07:46:01\', 1, 0, \'https://home.osuv.de/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjEwNzg5OCwib3duZXJJZCI6Im0iLCJzaGFyZVRva2VuIjpudWxsLCJhY3Rpb24iOiJ0cmFjayJ9.ud-gFvlbT7GIEqa0Yh2tfKxXyJIvRsY9oXN9eMl5nOY\', \'https://office.osuv.de\') ON DUPLICATE KEY UPDATE last_open_date = \'2019-10-07 07:46:01\', user_index = LAST_INSERT_ID(user_index + 1);' }
office.1.p48z15k2u418@hetzner    | [2019-10-07T07:46:01.951] [ERROR] nodeJS - _____________________end_error_____________________
office.1.p48z15k2u418@hetzner    | [2019-10-07T07:46:01.952] [ERROR] nodeJS - error receiving response: docId = null type = auth
```

because all tables does not exists

`/var/www/onlyoffice/documentserver/server/schema/mysql/createdb.sql` this must be applied with `mysql-client`, which is not included in the image. 
The hole `psql` section must be skipped when `DATABASE_TYPE` is `mysql`

When I apply the schema by my own with my patched Dockerfile, it works.

**Comment by ShockwaveNN** [comment]
@markuman Oh, sorry my bad, currently we support mysql only via `rpm` installation (with some limitations), not on `deb` or `Docker image`

**Comment by markuman** [comment]
@ShockwaveNN I've forked it and try to fix it.  
Init the mysql schema works fine,

What doesn't work it to update the default.json  
it stays at the default after initialization has completed
any ideas about it? https://github.com/markuman/Docker-DocumentServer/commit/1329c55a2cac9a91edb5cd9cd6c431d5fdc2d11c#diff-85cd1b1370d70832d345fb65043c8a48R146


```
root@1e52256a2e41:/# grep postgres /etc/onlyoffice/documentserver/default.json -A 11
				"type": "postgres",
				"tableChanges": "doc_changes",
				"tableResult": "task_result",
				"dbHost": "localhost",
				"dbPort": 5432,
				"dbName": "onlyoffice",
				"dbUser": "onlyoffice",
				"dbPass": "onlyoffice",
				"charset": "utf8",
				"connectionlimit": 10,
				"max_allowed_packet": 1048575
```

> with some limitations

What are the mysql limitations?

**Comment by ShockwaveNN** [comment]
@agolybev take a look

**Comment by markuman** [comment]
Okey, I noticed that the changes are written into `/etc/onlyoffice/documentserver/local.json` but the `type` value in the `sql` object seems to have no effect in the `local.json`. I need to sed it in the `default.json` to make it work.

**Comment by markuman** [comment]
Okey - using  a remote database is useless in most cases.  
My memory consumption on an initialized and idling documentserver is reduced by 16MB when using a remote mariadb. But it looks like that only data on opened documents (and for collaboration) is temporary saved there. So in general - there is absolut **no** need for a remote database - expect that you need to scale the documentserver (docker swarm mode, k8s ...). But in that case, you need also to use a remote redis and a remote rabbitmq!  
And when you use a remote db, it must be very close to the documentserver, otherwise it is to slow for collaboration and it will results in error on doublicated keys. E.g. don't try aws rds/aurora.

Just my 2 cents.
