### ISSUE TITLE
Can't access Netcloud files "The files could not be saved"

### ISSUE THREAD

**Issue by stemeinke** [ONLYOFFICE/Docker-DocumentServer#130]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/42817856/46660932-7577b300-cbb8-11e8-8f02-6618f7deeb1b.png)
When I click on a file in nextcloud the error above appears. 
The error says that the file could not be saved (like these [issue](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/114))

**Logs**
When I do the docker logs _container-id_ these error is shown after I try to open a file.
/var/log/onlyoffice/documentserver/docservice/out.log <==

```
[2018-10-09 09:23:25.486] [ERROR] nodeJS - postData error: docId =3369593812;url =http://<nextcloud.domain.tld>/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjI0MDQsIm93bmVySWQiOiJTdGVmZmVuIiwidG9rZW4iOm51bGwsImFjdGlvbiI6InRyYWNrIn0.vEhw5LcrA_unKBj94tSZXnBzOuY-MmF4K0el1FSNy88;data = {"key":"3369593812","status":1,"users":["username"],"actions":[{"type":1,"userid":"username"}]}Error: Error response: statusCode:301 ;body:

at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:283:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Co mmon/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

    

**What is the expected behavior?**
Editing a file in OnlyOffice
**DocumentServer Docker tag:**
5.2.0
**Nextcloud version:**
14.0.1
**Host Operating System:**
Ubuntu 18.04 LTS

**Comment by ShockwaveNN** [comment]
Please duplicate your issue at https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues
