### ISSUE TITLE
Disconnection Error when multiple edit: TypeError

### ISSUE THREAD

**Issue by keomabrun** [ONLYOFFICE/Docker-DocumentServer#159]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When multiple users are editing the same file at the same time, sometimes, one use get disconnected.

Here is the corresponding error in `docservice/out.log`
```
[2019-05-15T16:35:08.126] [ERROR] nodeJS - error receiving response: docId = null type = unLockDocument
TypeError: Cannot read property 'id' of undefined
    at /var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:1108:80
    at Generator.next (<anonymous>)
    at onFulfilled (/var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:65:19)
    at /var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:50:10)
    at SockJSConnection.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:1055:14)
    at emitOne (events.js:116:13)
    at SockJSConnection.emit (events.js:211:7)
    at Session.didMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/sockjs/lib/transport.js:246:25)
    at App.xhr_send (/var/www/onlyoffice/documentserver/server/DocService/node_modules/sockjs/lib/trans-xhr.js:81:15)
    at execute_request (/var/www/onlyoffice/documentserver/server/DocService/node_modules/sockjs/lib/webjs.js:22:37)
    at req.next_filter (/var/www/onlyoffice/documentserver/server/DocService/node_modules/sockjs/lib/webjs.js:105:18)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/sockjs/lib/webjs.js:298:18)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
[2019-05-15T16:35:15.056] [WARN] nodeJS - error description: docId = 2952317939 errorId = Restore error. Document modified.
```
Here is the error on the client side (Firefox 60.6.2 [esr)]:
"Impossible d'accéder au fichier" (french version).

The CPU and RAM (16G available) usage seem low (<10%) on average. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I was not able to reproduce the error easily. The only way is to edit the document with multiple persons.

**What is the expected behavior?**

No being disconnected.

**Did this work in previous versions of DocumentServer?**

No.

**DocumentServer Docker tag:**
Latest

**Host Operating System:**

Debian stretch
DocumentServer CE v5.2.8

**Comment by ShockwaveNN** [comment]
Hi, what document management system do you use? Owncloud, Nextcloud, ONLYOFFCE Community, test example?

**Comment by keomabrun** [comment]
Thanks for you feedback! I use Nextcloud.

**Comment by ShockwaveNN** [comment]
We think the reason of this errors is bad networking, connection to websocket lost and if connection is lost and there is some new changes from other user - after restoring connection there will be such error

**Comment by keomabrun** [comment]
I don't think this is the case. This test was performed by two persons, with two browser sessions per person (in incognito mode), on a robust network. On of the four session disconnected after a few minute of edition.

**Comment by ShockwaveNN** [comment]
@keomabrun Could you reproduce this situation on Chrome? There is difference in working with WebSocket in Chrome and Firefox and by your error log seems there is a problem establishing websocket connection and `xhr` used instead

**Comment by keomabrun** [comment]
Alright :) I will try that. Thanks!

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
