### ISSUE TITLE
cannot loading file larger 5MB

### ISSUE THREAD

**Issue by olivy70** [ONLYOFFICE/Docker-DocumentServer#242]
Hi,
My environnement :
Unbuntu 16.04 TLS
PHP7/Nginx
Nextcloud 16
onlyoffice/documentserver last docker version
Installation guide from https://riegers.in/nextcloud-and-only-office-nginx/

The problem appears for files larger than 5MB.

Here is the out.log
==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2020-03-24T08:28:12.961] [ERROR] nodeJS - error downloadFile:url=https://MYURL/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjQ0MDk0NCwidXNlcklkIjoib2xpdmllci5wcmFkaWVyIiwic2hhcmVUb2tlbiI6bnVsbCwiYWN0aW9uIjoiZG93bmxvYWQifQ.GYRae6RvXNCRDjacKQ4DZEsl68BAD8wke42CtRbtNnk;attempt=1;code:ESOCKETTIMEDOUT;connect:false;(id=2550348282)
Error: ESOCKETTIMEDOUT
at ClientRequest. (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
at Object.onceWrapper (events.js:286:20)
at ClientRequest.emit (events.js:198:13)
at TLSSocket.emitRequestTimeout (_http_client.js:662:40)
at Object.onceWrapper (events.js:286:20)
at TLSSocket.emit (events.js:198:13)
at TLSSocket.Socket._onTimeout (net.js:443:8)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)

A little help ?
Thanks !

**Comment by ShockwaveNN** [comment]
This error seems because DocumentServer server cannot download file from nextcloud with default timeout. 

I think you should check your network connection between netxcloud server and DocumentServer

**Comment by olivy70** [comment]
@ShockwaveNN 
it's strange because it's the same server :/

**Comment by ShockwaveNN** [comment]
Any special params or keys you used to run documentserver docker?

**Comment by olivy70** [comment]
@ShockwaveNN 
nothing special.
this is the install guide I used : https://riegers.in/nextcloud-and-only-office-nginx/

**Comment by ShockwaveNN** [comment]
Yeah, accroding to this guide docker run is pretty standart:
```
docker run --name=ONLYOFFICEDOCKER -i -t -d -p 8443:443 -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data -e JWT_ENABLED='true' -e JWT_SECRET='yoursecret' --restart=always onlyoffice/documentserver
```

So I think this problem is not related with Docker-DocumentServer, but with integration to nextcloud, so I move this issue to another repo
