### ISSUE TITLE
The container becomes big suddenly in FileConverter

### ISSUE THREAD

**Issue by Philippe34** [ONLYOFFICE/Docker-DocumentServer#333]
Hi,

The "overlay" suddenly magnifies by several GB. For instance, the size is 44 G / 69 G available

`df -h`
`overlay             69G     44G   25G  64% /var/lib/docker/overlay2/23a1920840f17d73f2255fd8c59fd4b161a384beb7f5c599875c408bd2c8ec9e/merged`

My research leads me to : /var/www/onlyoffice/documentserver/server/FileConverter/
and core.xxxx files (the bigger is 6 GB)

`docker exec -t -i agitated_dhawan /bin/bash`
```
ls -l /var/www/onlyoffice/documentserver/server/FileConverter/
total 32338104
drwxr-xr-x. 1 ds ds       4096 Aug  5  2020 bin
-rwxr-xr-x. 1 ds ds   65356956 Aug  5  2020 converter
-rw-------. 1 ds ds 2805067776 Jan 11 13:53 core.12072
-rw-------. 1 ds ds 2223337472 Dec 15 08:33 core.13172
-rw-------. 1 ds ds 7956340736 Feb  7 00:39 core.1403
-rw-------. 1 ds ds 2211958784 Dec 11 15:21 core.16497
-rw-------. 1 ds ds 3674165248 Jan 15 08:53 core.1932
-rw-------. 1 ds ds 2999435264 Jan  6 22:54 core.20952
-rw-------. 1 ds ds 6686732288 Feb  6 19:05 core.24825
-rw-------. 1 ds ds  886530048 Jan 15 08:56 core.2577
-rw-------. 1 ds ds  205795328 Jan 15 09:05 core.3184
-rw-------. 1 ds ds 3399168000 Dec 16 16:45 core.32180
-rw-------. 1 ds ds     180224 Jan 15 09:09 core.3761
drwx------. 2 ds ds         75 Dec  1 12:06 GPUCache
```

I wonder why theses files are suddenly created . 
Can I safely erase these files to gain several tens of GB

Thanks

**Comment by ShockwaveNN** [comment]
@Philippe34 Hm, never seen those, maybe those are core dumps of major failures
Is there any errors in `/var/log/onlyoffice/converter`?

**Comment by Philippe34** [comment]
Hi @ShockwaveNN 

When the even happens, there are errors with "files not found"

```
[2021-02-05T15:18:11.412] [ERROR] nodeJS - error spawnAsync(id=conv_1115181878_jpeg)^M
Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGTERM
    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:51:23)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js:0:0)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2021-02-05T15:18:11.439] [ERROR] nodeJS - stdout (id=conv_1115181878_jpeg):
[2021-02-05T15:18:11.439] [ERROR] nodeJS - stderr (id=conv_1115181878_jpeg):
[2021-02-05T15:18:11.439] [ERROR] nodeJS - ExitCode (code=0;signal=SIGTERM;error:-83;id=conv_1115181878_jpeg)
[2021-02-05T15:18:11.768] [ERROR] nodeJS - error downloadFile:url=https://cloud.domain.fr/owncloud/index.php/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJkb3dubG9hZCIsImZpbGVJZCI6NDExMDk3NTgsInVzZXJJZCI6ImZjNTA4MWUyLTZhZjEtMTAzOC05ZWFiLWU1MjNmN2UzNzI5NiJ9.PhMiv7Tn66mT03oa4qC2YcjK6aNGwWwwfBs4KnlsCIg;attempt=1;code:null;connect:null;(id=conv_3444835299_jpeg)^M
Error: Error response: statusCode:404 ;body:^M
{"message":"Fichiers introuvables"}
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2021-02-05T15:18:12.832] [ERROR] nodeJS - error downloadFile:url=https://cloud.domain.fr/owncloud/index.php/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJkb3dubG9hZCIsImZpbGVJZCI6NDExMDk3NTgsInVzZXJJZCI6ImZjNTA4MWUyLTZhZjEtMTAzOC05ZWFiLWU1MjNmN2UzNzI5NiJ9.PhMiv7Tn66mT03oa4qC2YcjK6aNGwWwwfBs4KnlsCIg;attempt=2;code:null;connect:null;(id=conv_3444835299_jpeg)^M
Error: Error response: statusCode:404 ;body:^M
{"message":"Fichiers introuvables"}
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
```
Should I do an Onlyoffice update ?

**Comment by ShockwaveNN** [comment]
> When the even happens, there are errors with "files not found"

I think this not on `file not found` error, but on SIGTERM

```
Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGTERM
```

> Should I do an Onlyoffice update ?

We got SIGTERM bug in some versions ago, don't quite remember exactly, but around version 6.0.2

So anyway, if you using not the latest version, not a 6.1.1 - I advise you to update and see if this error happens again

**Comment by Philippe34** [comment]
OK I'm late. It is the 5.6.0 version that is running.
So I will update.
What do you think about the link with jpeg errors ?
`id=conv_3444835299_jpeg`

Thank you

**Comment by ShockwaveNN** [comment]
I think 404 errors are happens on integration side, Nextcloud or something other that you're using, but they shouldn't generate core files as I think

You defenitly should update, 5.6 is pretty old and we're not supporting this version

**Comment by Philippe34** [comment]
Il will update as possible.
Il will be back if it issue continues.

Thank you  very much @ShockwaveNN for your help.

**Comment by Philippe34** [comment]
I updated OnlyOffice to 6.1.1 and now everything is good in FileConverter (no core files)

```
ls -l /var/www/onlyoffice/documentserver/server/FileConverter/
total 66560
drwxr-xr-x. 1 ds ds     4096 Jan 28 15:51 bin
-rwxr-xr-x. 1 ds ds 68150199 Jan 24 22:48 converter
```
Regards

**Comment by Philippe34** [comment]
Hi,
After a few days with good operation in Office 6.1.1, the issue reappeared again and it makes two big core.XXXX files
What should I do ?

My logs:

```
[2021-02-16T15:24:10.728] [ERROR] nodeJS - error spawnAsync(id=conv_2877890330_jpeg)^M
Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGILL
    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:51:23)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js:0:0)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2021-02-16T15:24:10.729] [ERROR] nodeJS - stdout (id=conv_2877890330_jpeg):
[2021-02-16T15:24:10.729] [ERROR] nodeJS - stderr (id=conv_2877890330_jpeg):
#
# Fatal javascript OOM in CALL_AND_RETRY_LAST
#

Received signal 4 ILL_ILLOPN 7fb707664849

==== C stack trace ===============================

 [0x7fb707665a92]
 [0x7fb706a7b3c0]
 [0x7fb707664849]
 [0x7fb706e802dd]
 [0x7fb706e804dc]
 [0x7fb70704d9bf]
 [0x7fb7075c3adc]
 [0x34b70c3046fd]
[end of stack trace]


[2021-02-16T15:24:10.729] [ERROR] nodeJS - ExitCode (code=0;signal=SIGILL;error:-83;id=conv_2877890330_jpeg)
[2021-02-16T15:24:11.642] [ERROR] nodeJS - error downloadFile:url=https://cloud.domain.fr/owncloud/index.php/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJkb3dubG9hZCIsImZpbGVJZCI6NDEyMDc1NjcsInVzZXJJZCI6ImZjNTA4MWUyLTZhZjEtMTAzOC05ZWFiLWU1MjNmN2UzNzI5NiJ9.yVeU96CzZviN0LdtKJhTBOsK4bXF2Dt9HA2OY7epDzs;attempt=1;code:EMSGSIZE;connect:null;(id=conv_1068510181_jpeg)^M
Error: Error response: content-length:150113524
    at raiseError (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.<anonymous> (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.emit (events.js:198:13)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:203:15)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17)
```
Thanks

**Comment by ShockwaveNN** [comment]
1. Is there enough ram for usage of DocumentServer? 2gb ram and 4gb swap is required, if DocumentServer installed on dedicated instance
2. I think this error may occur while opening\trying to save some specific file, if you will be able to figure out which file causing it - please attach it to this issue

**Comment by Philippe34** [comment]
1. The DocumentServer operates on a machin with 16 GB ram at 3 GB swap. So for you, I should increase the size of swap to 4 GB
2. I can't figure out what Onlyoffice does when the core dump occurs.
On the owncloud server, I can see 3 documentServer connections:

```
onlyofficeIP - - [19/Feb/2021:21:58:12 +0100] "GET /owncloud/index.php/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJkb3dubG9hZCIsImZpbGVJZCI6NDEyODU4NTQsInVzZXJJZCI6ImZjNTA4MWUyLTZhZjEtMTAzOC05ZWFiLWU1MjNmN2UzNzI5NiJ9.3wwP0inQB440ljglJkr9Kguga2KxPFcEk4C-fagthCQ HTTP/1.1" 200 156032005
onlyOfficeIP- - [19/Feb/2021:21:58:12 +0100] "GET /owncloud/index.php/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJkb3dubG9hZCIsImZpbGVJZCI6NDEyODU4NDcsInVzZXJJZCI6ImZjNTA4MWUyLTZhZjEtMTAzOC05ZWFiLWU1MjNmN2UzNzI5NiJ9.Vul8NsDZtE_fKJ_GVe-9P5VBBhRR08F5akXT0bvH9mY HTTP/1.1" 200 155682874
onlyOfficeIP - - [19/Feb/2021:21:58:13 +0100] "GET /owncloud/index.php/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJkb3dubG9hZCIsImZpbGVJZCI6NDEyODU5MDYsInVzZXJJZCI6ImZjNTA4MWUyLTZhZjEtMTAzOC05ZWFiLWU1MjNmN2UzNzI5NiJ9.4gzxxkHhHCVU1dAM7IQBn-uWWNbF8W4I-ezL657o_ZY HTTP/1.1" 200 128
```
I can't make a link between these connections and an action of a user. 
And the size seems important (156 MB, 155 MB and 128 Bytes).
Maybe the size of the file that is downloaded is too large ?

**Comment by Philippe34** [comment]
I deleted the swap file and created an new 4GB swap.

**Comment by Philippe34** [comment]
A few seconds before the core dumps in the OnlyOffice container, i can see these kernel errors in the docker machine (libdoctrenderer.se)
```
Feb 19 21:54:16 docker kernel: traps: x2t[23521] trap invalid opcode ip:7fec9947e849 sp:7fffa503f928 error:0 in libdoctrenderer.so[7fec98ad3000+f9b000]
Feb 19 21:54:16 docker abrt-hook-ccpp: Process 5696 (x2t) of user 109 killed by SIGILL - dumping core
```

**Comment by ShockwaveNN** [comment]
> The DocumentServer operates on a machin with 16 GB ram at 3 GB swap. So for you, I should increase the size of swap to 4 GB

16GB is enough, so 3 gb swap is good

> Feb 19 21:54:16 docker abrt-hook-ccpp: Process 5696 (x2t) of user 109 killed by SIGILL - dumping core

This is new for me, never seen such error
According to google this error may be from incorrect architecture of application, not sure

Could you describe 
1. your host os and version
2. Is it x64?
3. Are you using our official image of `onlyoffice/documentserver`? What is output of `docker images | grep onlyoffice/documentserver`?

**Comment by Philippe34** [comment]
My host is an VM built on CentOS 7.9.2009
```
# uname -a
Linux docker 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Since the beginning in 2018 that I use OnlyOffice, I had never seen these dumping cores. In 2020 November 23, i upgraded from centOS 7.8 to 7.9, and the first dumps appeared the December 11.

Yes, I use your official image of onlyoffice/documentserver.

```
# docker images | grep onlyoffice/documentserver
onlyoffice/documentserver   latest    289798f72e62   3 weeks ago    2.45GB
onlyoffice/documentserver   <none>    e7f53e4bfa86   6 months ago   2.16GB
```
I can see 2 solutions:
1. Waiting for the next centOS 7.10 release of the docker machine
2. Moving the VM to a more recent KVM hypervisor which is actually on a centOS 6.10. I could migrate the VM on a  Cent0S 8.3 hypervisor.

Thank your very much ShockwaveNN for the time you spend on this weird issue.

**Comment by ShockwaveNN** [comment]
@Philippe34 I'm not sure that centos itself is the issue

You can try to rule this out by temporaly setup another DocumentServer, for example on ubuntu 18 + docker (this version we usally use in testing of DocumentServer) and see if this core files happens on this setup.

**Comment by Philippe34** [comment]
Can Ubuntu 20.04 LTS be used ?
Is an Ubuntu installed on a VM well supported ?

**Comment by ShockwaveNN** [comment]
@Philippe34 Yes, of course. You can use Ubuntu 20.04 and install on VM

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
