### ISSUE TITLE
DB_TYPE mysql 8.0.17 connect fail

### ISSUE THREAD

**Issue by odeng888** [ONLYOFFICE/Docker-DocumentServer#364]
[2021-06-18T09:25:26.821] [ERROR] nodeJS - pool.getConnection error: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
[2021-06-18T09:25:26.822] [ERROR] nodeJS - error receiving response: docId = undefined type = auth
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/snapshot/server/build/server/DocService/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/snapshot/server/build/server/DocService/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/snapshot/server/build/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/snapshot/server/build/server/DocService/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/snapshot/server/build/server/DocService/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/snapshot/server/build/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/snapshot/server/build/server/DocService/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/snapshot/server/build/server/DocService/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by ShockwaveNN** [comment]
@odeng888 Hi, could you provide minimal docker-compse to reproduce this issue?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
