### ISSUE TITLE
502 Bad Gateway and some openpgp.js issue

### ISSUE THREAD

**Issue by XiaoPengCn** [ONLYOFFICE/Docker-DocumentServer#366]
When using OnlyOffice DocServer in docker which managed by rancher, I got `502 Bad Gateway` response with request `/6.3.1-32/doc/FiHMtmMo3j1oWKp/c/info?t=1625032893491`

```
==> /var/log/onlyoffice/documentserver/converter/err.log <==
pkg/prelude/bootstrap.js:1244
      throw error;
      ^
Error: Configuration property "openpgpjs.encrypt" is not defined
    at Config.get (/snapshot/server/build/server/Common/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:25:18)
==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2021-06-30T06:47:37.358] [WARN] nodeJS - worker 5599 died (code = 1; signal = null).
[2021-06-30T06:47:37.360] [WARN] nodeJS - worker 5605 started.
==> /var/log/onlyoffice/documentserver/converter/err.log <==
pkg/prelude/bootstrap.js:1244
      throw error;
```
**DocumentServer Docker tag: 6.3.1** maybe

**Host Operating System:**

**Comment by ShockwaveNN** [comment]
I think this may be because we do not officially supporting rancher.

Error looks like config files are missing
Is DocumentServer container has configs inside it's container in `/etc/onlyoffice/documentserver/`?

**Comment by XiaoPengCn** [comment]
Thanks for reply. here's files list in `/etc/onlyoffice/documentserver/`:
`default.json  development-linux.json  development-mac.json  development-windows.json  local.json  log4js  logrotate  nginx  production-linux.json  production-windows.json  supervisor`


and I posted a detail log file, may you take a look at it please?
[start_log.log](https://github.com/ONLYOFFICE/Docker-DocumentServer/files/6738673/start_log.log)

**Comment by ShockwaveNN** [comment]
Judging by the logs converter service cannot read configuration file, so I'm not good at all at rancher - but maybe some permission issues?

Could you run usual Docker container and compare access right between Docker and rancher or maybe something related to them?

**Comment by XiaoPengCn** [comment]
Thanks a lot!
It turns out that rancher mounts a data volume to the configuration file automatically. 
I unmounted it and DocumnetServer worked just fine!

**Comment by ShockwaveNN** [comment]
@XiaoPengCn Glad to hear
