### ISSUE TITLE
[ERROR] nodeJS - Error saveChanges

### ISSUE THREAD

**Issue by acsfer** [ONLYOFFICE/Docker-DocumentServer#393]
My Entreprise Docker image is full of these logs (only 2 lines here but they are repeated thousands of times).

Please let me know if you need further informations.

```
[ERROR] nodeJS - Error saveChanges docid: 3003692539 ; deleteIndex: 91 ; startIndex: 81 ; deleteCount: -10

[ERROR] nodeJS - changesError: docId = 3003692539 x.prototype.jEf@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:1239:1
x.prototype.ia@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:1233:501
Nc.prototype.dQ@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:7190:489
Nc.prototype.RVd@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:7222:459
Nc.prototype.CWd@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:7218:380
Nc.prototype.nwg@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:7184:240
yc.prototype.F7g@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:7082:155
RJh@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:8444:256
x.prototype.close@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:7915:373
x.prototype.rsh@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:7962:490
x.prototype.jIf@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:7965:413
Da.prototype.VX/this.Hc.Roa@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:8038:352
Roa@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:13461:89
oe/this.bs.onkeydown@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:13444:284

[ERROR] nodeJS - error spawnAsync(id=1717261985)
Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGTERM
    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:51:23)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js:0:0)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

[ERROR] nodeJS - stdout (id=1717261985_2882):
[ERROR] nodeJS - stderr (id=1717261985_2882):
[ERROR] nodeJS - ExitCode (code=0;signal=SIGTERM;error:-83;id=1717261985_2882)
```

**Comment by ShockwaveNN** [comment]
Do you have some other problems in files except for logs?

Because I don't know exactly when `changesError: ` happened, but as far as I'm aware this may be because some of users didn't cleared cache and maybe some scripted got messedup up. Just an idea, not 100% sure

But anyway until we can reproduce this issue on our installation I don't think we can help somehow with this error

**Comment by acsfer** [comment]
As you can see with `Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGTERM` yes this is a problem because file has not been converted and so, an error like 'File not found" is trown ad the DMS (Nextcloud). 🤔

**Comment by ShockwaveNN** [comment]
I think `[ERROR] nodeJS - changesError: docId = 3003692539 x.prototype.jEf@https://example.com/onlyoffice/6.4.2-6/sdkjs/cell/sdk-all.js:1239:1` and `Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGTERM` may be unrelated, but judging by logs I have no idea that do to, only to reproduce this situation

**Comment by acsfer** [comment]
As far as i can see, there are similar issues like https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/333#issuecomment-776810985 (closed due to lack of feedback).

We operate on a (VM) server on Ubuntu 20.04, latest `docker-ce` and `onlyoffice-ee` with 4G RAM and 4GB SWAP so this should not be a system/hardware issue.

**Comment by ShockwaveNN** [comment]
@acsfer Yeah, I've alreay found this issue - and that issue was a mess, a lot of unrelated problems as far as I remember

> 4G RAM and 4GB SWAP so this should not be a system/hardware issue.

Could you clarify - do you have only `onlyoffice-documentserver-ee` on this system or both documentserver and `communityserver`?

**Comment by acsfer** [comment]
> Could you clarify - do you have only onlyoffice-documentserver-ee on this system or both documentserver and communityserver?

`onlyoffice-documentserver-ee` only is installed.

**Comment by ShockwaveNN** [comment]
Yeah, for only DocumentServer 4g ram and 4gb swap is enogth

So I agree that seems that this problem is not related to hardware, but I have no ideas how to reproduce it and moreover to fix it

I'll leave this issue opened, maybe someone have some ideas

**Comment by brendan-pike** [comment]
I think I may be experiencing this issue, it occurs on a specific document with tracked changes when I perform a find/replace.
`[2022-05-18T01:42:25.010] [ERROR] nodeJS - changesError: docId = 3643338939 Error: TypeError: this.aa[b] is undefined Script: https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js Line: 7325:189 userAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0 platform: Linux x86_64 isLoadFullApi: true isDocumentLoadComplete: true StackTrace: cg.prototype.hU@https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:7325:189
Rf.prototype.hU@https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:7713:195
Rf.prototype.Ar@https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:7666:396
Fx.prototype.EQ@https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:9696:203
xf.prototype.Qkd@https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all.js:9699:244
Nb.prototype.u5f@https://mydomain.com/7.0.1-37/sdkjs/word/sdk-all-min.js:1106:61
onQueryReplaceAll@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:68:18839
M@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8:11759
m.bind</n<@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8:11961
f/<@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8:5162
fireEvent/</<@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13:15753
m.forEach@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8:5805
fireEvent/<@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13:15732
g/<@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8:4766
m.forEach@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8:5865
fireEvent@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13:15652
fireEvent@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:13:15157
onBtnClick@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:20:14320
M@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8:11759
m.bind</n<@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8:11961
f/<@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:8:5162
dispatch@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:10:9782
add/b.handle@https://mydomain.com/7.0.1-37/web-apps/apps/documenteditor/main/app.js:10:7756`

**Comment by ShockwaveNN** [comment]
@brendan-pike I don't think it's the same error, since error text look different

I need you to 
1. Update to latest v7.1.0 and check if this error still occurs
2. If it's occurred - please create a new issue with step-by-step description (and probably file on which this error occurs) how to reproduce this problem
