### ISSUE TITLE
Reverse proxy Nginx not working as expected

### ISSUE THREAD

**Issue by zadrarion** [ONLYOFFICE/Docker-DocumentServer#403]
**Do you want to request a *feature* or report a *bug*?**
Bug

I've setup a really simple docker documentserver in standard http with a nginx reverse proxy for https deliver by let's encrypt.
I turning on the example for try purpose and i always get :
![image](https://user-images.githubusercontent.com/13852927/152234147-207946b6-d1ea-4a1d-9002-f1647b8e1ce8.png)
![image](https://user-images.githubusercontent.com/13852927/152234232-b67b8477-6150-4e4f-ae86-c86dfb734e9d.png)

i've try many option :
- setup https only with the documentserver container -> work but i really need reverse proxy
- setup only a reverse proxy with https -> not work
- http only -> work as expected
- use nginx proxy manager -> same problem, not work only for read document with same error

the log from the documentserver container:
```
[2022-02-02T20:43:16.087] [ERROR] nodeJS - error downloadFile:url=https://onlyoffice.xxx.xx/download?fileName=new.docx&useraddress=xx.xx.xx.xx__172.16.8.247;attempt=3;code:null;connect:null;(id=xx.xx.xx.xx__172.16.8.247https___onlyoffice.z-medley.fr_files_xx.xx.xx.xx__172.16.8.247_new.docx1643813341423)
Error: Error response: statusCode:404; headers:{"server":"nginx","date":"Wed, 02 Feb 2022 20:43:16 GMT","content-type":"text/html","transfer-encoding":"chunked","connection":"keep-alive","content-encoding":"gzip"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

My nginx configuration for onlyoffice
```
map $http_host $this_host {
    "" $host;
    default $http_host;
}

map $http_x_forwarded_proto $the_scheme {
     default $http_x_forwarded_proto;
     "" $scheme;
}

map $http_x_forwarded_host $the_host {
    default $http_x_forwarded_host;
    "" $this_host;
}

map $http_upgrade $proxy_connection {
  default upgrade;
  "" close;
}

gzip off;

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Forwarded-Host $the_host;
proxy_set_header X-Forwarded-Proto $the_scheme;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Real-IP $remote_addr;

server {
    listen 0.0.0.0:443 ssl;
    listen [::]:443 ssl;
    server_name onlyoffice.xxxxx.xx
    server_tokens off;
    root /usr/share/nginx/html;

    ssl_certificate /etc/nginx/certs/onlyoffice.crt;
    ssl_certificate_key /etc/nginx/certs/onlyoffice.key;
    ssl_verify_client off;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_prefer_server_ciphers   on;

    add_header X-Content-Type-Options nosniff;
    
    location / {
      proxy_pass http://172.16.8.250:80/;
      proxy_buffers 4 256k; 
      proxy_max_temp_file_size 0;
      proxy_http_version 1.1;
  }
}
```

i don't know if the problem happened on previous version of the container.
Docker is setup on this VM
![image](https://user-images.githubusercontent.com/13852927/152235151-a1afa780-0646-4e4c-bf32-3128757e86c6.png)

i don't know what i doing wrong, i have setup all the content with this pages:
https://helpcenter.onlyoffice.com/en/installation/docs-community-install-docker.aspx
https://helpcenter.onlyoffice.com/en/installation/docs-community-proxy.aspx

**Comment by igwyd** [comment]
Hello @zadrarion, nginx and onlyoffice-documentserver installed on the same vitrual machine?

**Comment by zadrarion** [comment]
Hello @igwyd, no they are on two distinct virtual machine

**Comment by igwyd** [comment]
Documentserver work with nginx reverse proxy, you can check it when connecting to integrators ([all connectors](https://www.onlyoffice.com/en/all-connectors.aspx)). Dont work only included test example in documentserver-7.0.0.132 with reverse proxy. We fix it in next major release.

**Comment by jbouza** [comment]
Hello @igwyd, 
I have a same problem of @zadrarion; but the example is working with https and revese proxy; 

![image](https://user-images.githubusercontent.com/24595230/153777485-126334a6-0ebf-40cc-8e3b-84ff8569d5d2.png)

![image](https://user-images.githubusercontent.com/24595230/153777479-f76b4b89-93dc-4b8c-be92-e0ef6cf4150c.png)

but I try connect nextcloud in log register this error

`[2022-02-13T21:46:37.686] [ERROR] nodeJS - error downloadFile:url=https://nextcloud.example.com/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.--yNIqMHopaTeZkUeOo31MB2GcVQxPE0gSWQi3ovVBE;attempt=3;code:null;connect:null;(id=conv_check_1943680295_docx)
Error: Error response: statusCode:503; headers:{"server":"nginx/1.18.0 (Ubuntu)","date":"Sun, 13 Feb 2022 21:46:37 GMT","content-type":"text/html; charset=UTF-8","transfer-encoding":"chunked","connection":"keep-alive","expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","set-cookie":["oc_sessionPassphrase=iAI3eKxDJLq8pBAGLM0OaMAJwjdkLoTgWSbv90V6IntBcvTRzL1xNIXfbsDFJ7B%2Fi72mBkkCdX%2BLogGbhBX1j2rFUEye%2Fu0xk1UVY%2B6R%2BE9hYgLSwCg%2BpUuUqgjWxEMG; path=/; secure; HttpOnly; SameSite=Lax","ocua0snksza7=kallehsb2ol3stvr7o2e213qut; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict"],"content-security-policy":"default-src 'self'; script-src 'self' 'nonce-N3dzWVFCdE1GK0dXeUk4OUlWRmhiNTFjamZ2UmswbFlXY1FReExKRUN1dz06dGx0dGVHZ09RdFh3cGFSMVppVXNPUEF6eHBpVjZnd0phYlIwa05VTlJ0dz0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-download-options":"noopen","x-permitted-cross-domain-policies":"none","x-robots-tag":"none","x-xss-protection":"1; mode=block"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)`


and nextcloud show this messages

`Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 7.0.0.132)`

I have installed nextcloud and onlyoffice in differents virtual machine, I using Ubuntu 20.04 in both, and installed onlyoffice by this guide [https://helpcenter.onlyoffice.com/de/installation/docs-community-install-ubuntu.aspx](https://helpcenter.onlyoffice.com/de/installation/docs-community-install-ubuntu.aspx)

**Comment by ant0nwax** [comment]
Hi @ShockwaveNN i came until this bug here

and I see that the bug i reported (https://github.com/ONLYOFFICE/DocumentServer/issues/1659)
is more or less valid becasue i still cannot work with xls or ods, they open in the viewer in Nextcloud and not in the editor on desktop browser

so for this bug I am curious when will 7.1 be released

i am now only testing with the example and honestly NEXTcloud works better than the example :)

My setup for https://onlyoffice.comain.tld/example :

browser -> apache (httpd) https -> nginx https -> document-server


steps:

precondition:  /etc/onlyoffice/documentserver/default.json
`                        "requestDefaults": {
                                "agentOptions": {
                                        "ca": "/etc/pki/nginx/chain.pem"
                                },
                                "headers": {
                                        "User-Agent": "Node.js/6.13",
                                        "Connection": "Keep-Alive"
                                },
                                "gzip": true,
                                "rejectUnauthorized": false
`

1. supervisorctl restart all && service nginx restart
2. fresh incognito chrome browser
3. navigate to https://onlyoffice.DELETED/example/
4. Upload file: test.xlsx (1,2,3 will pass
5. Press EDIT

Expected, editing possible
Real result: same error messages 
- 1st Download failed 
- 2nd The document could not be saved... (like on the screenshots)

result: /var/log/onlyoffice/documentserver/docservice/out.log
`[2022-02-28T18:44:19.583] [WARN] nodeJS - Express server starting...
[2022-02-28T18:44:19.585] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2022-02-28T18:44:19.714] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 7.0.0. Build: 132
[2022-02-28T18:44:43.591] [ERROR] nodeJS - postData error: docId = 192.168.1.14https___onlyoffice.DELETED_files_192.168.1.14_test.xlsx1646070276157;url = https://onlyoffice.DELETED/track?filename=test.xlsx&useraddress=192.168.1.14;data = {"key":"192.168.1.14https___onlyoffice.DELETED_files_192.168.1.14_test.xlsx1646070276157","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}]}
Error: Error response: statusCode:404; headers:{"server":"nginx","date":"Mon, 28 Feb 2022 17:44:43 GMT","content-type":"text/html; charset=utf-8","transfer-encoding":"chunked","connection":"keep-alive","vary":"Accept-Encoding","x-powered-by":"Express","content-security-policy":"default-src 'none'","x-content-type-options":"nosniff","content-encoding":"gzip"}; body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /track</pre>
</body>
</html>

    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at Gunzip.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at Gunzip.emit (events.js:400:28)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
`

**Comment by adam-op** [comment]
I confirm on behalf of ant0nwax, that the issue that appeared on nginx side by using https inside of onlyoffice machine (not on the reverse proxy) and the reverse proxy is httpd (apache) with https, the issue is also solved, ant0nwax will continue on the other issue report...
