### ISSUE TITLE
Error occurred in the document service: Error while downloading the document file to be converted

### ISSUE THREAD

**Issue by LeoChaser** [ONLYOFFICE/Docker-DocumentServer#411]
Bug(?): Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 7.0.1.37)✖

**What is the current behavior?**

Cannot connect Nextcloud to Onlyoffice (both docker images) to edit documents. Used to work before.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Nextcloud and Onlyoffice Document Server both behind Linuxserver.io Swag proxy. There are these errors when trying to edit a document or when trying to connect to Onlyoffice in Nextcloud settings.

==> /var/log/onlyoffice/documentserver/converter/out.log <==

```
[2022-03-07T01:39:10.440] [ERROR] nodeJS - error downloadFile:url=https://cloud.example.com/apps/onlyoffice/empty?doc=BIGHASH;attempt=1;code:ECONNRESET;connect:null;(id=conv_check_417232190_docx)

Error: socket hang up

    at connResetException (internal/errors.js:628:14)

    at TLSSocket.socketOnEnd (_http_client.js:499:23)

    at TLSSocket.emit (events.js:412:35)

    at endReadableNT (internal/streams/readable.js:1317:12)

    at processTicksAndRejections (internal/process/task_queues.js:82:21)

[2022-03-07T01:39:11.442] [ERROR] nodeJS - error downloadFile:url=https://cloud.example.com/apps/onlyoffice/empty?doc=BIGHASH;attempt=2;code:ECONNRESET;connect:null;(id=conv_check_417232190_docx)

Error: socket hang up

    at connResetException (internal/errors.js:628:14)

    at TLSSocket.socketOnEnd (_http_client.js:499:23)

    at TLSSocket.emit (events.js:412:35)

    at endReadableNT (internal/streams/readable.js:1317:12)

    at processTicksAndRejections (internal/process/task_queues.js:82:21)

[2022-03-07T01:39:12.445] [ERROR] nodeJS - error downloadFile:url=https://cloud.example.com/apps/onlyoffice/empty?doc=BIGHASH;attempt=3;code:ECONNRESET;connect:null;(id=conv_check_417232190_docx)

Error: socket hang up

    at connResetException (internal/errors.js:628:14)

    at TLSSocket.socketOnEnd (_http_client.js:499:23)

    at TLSSocket.emit (events.js:412:35)

    at endReadableNT (internal/streams/readable.js:1317:12)

    at processTicksAndRejections (internal/process/task_queues.js:82:21)

```

**What is the expected behavior?**

Document editing working.

**Did this work in previous versions of DocumentServer?**

Yes. Welcome page works on HTTPS and healthcheck returns true.

**DocumentServer Docker tag:**

onlyoffice/documentserver:latest

**Host Operating System:**

Debian 11.2

**Comment by ShockwaveNN** [comment]
Hi, never had any exprieince with

>  Linuxserver.io Swag proxy

But this error seems like something wrong with networking

You can check it via connecting to DocumentServer container and try to `curl` this URL

like:
```
curl https://cloud.example.com/apps/onlyoffice/empty?doc=BIGHASH
```
and if there will be any error - this mean that problem is not on a DocumentServer side, but something wrong with networking

**Comment by LeoChaser** [comment]
There was a problem with my Nextcloud container after update. It's working now, thank you.
