### ISSUE TITLE
Onlyoffice dont save documents

### ISSUE THREAD

**Issue by SizerSong** [ONLYOFFICE/Docker-DocumentServer#430]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
1. After editing and saving the document, I quit editing and clicked the download button on the right of the document name on the 
home page to download the document, only to find that I downloaded the original uploaded version instead of the modified version
2. But when I downloaded the file in Edit mode, in the upper-left file option, everything became normal!

These logs appear in the docker container output:
```
[2022-04-22T10:20:38.551] [ERROR] nodeJS - sendServerRequest error: docId = 78babb86fbe95421ea83;url = https://thunderfile.leihuo.netease.com/onlyoffice/editor-callback/;data = {"key":"78babb86fbe95421ea83","status":6,"url":"https://thunderfile.leihuo.netease.com:1443/cache/files/78babb86fbe95421ea83_1211/output.xlsx/output.xlsx?md5=GxB2vr9wHG0IuBOYFaZGKg&expires=1650623729&filename=output.xlsx","history":{},"users":["uid-1650360496473"],"actions":[{"type":2,"userid":"uid-1650360496473"}],"lastsave":"2022-04-22T10:20:22.000Z","forcesavetype":1,"filetype":"xlsx"}
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:519:28)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.Socket._onTimeout (net.js:484:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**What is the expected behavior?**
downloading the latest version

**DocumentServer Docker tag:**
Docker installtion:
Package: onlyoffice-documentserver
Version: 7.0.1-37

**Host Operating System:**
Debian 10

**Comment by ShockwaveNN** [comment]
Hi, this may be network issue, for some reason DocumentServer cannot connect to DMS

We got similar issue 
https://github.com/ONLYOFFICE/DocumentServer/issues/1453 (something wrong with proxy)
https://github.com/ONLYOFFICE/DocumentServer/issues/1702 - WOPI related

Judging by you log - is https://thunderfile.leihuo.netease.com host accesable from inside of DocumentServer container?

**Comment by SizerSong** [comment]
@ShockwaveNN 
Sorry for reply you so late, I tried to modify the firewall rule: allow onlyoffice docker subnet to access all port in this server, and the problem was fixed.
But i still don't understand why, I've opened the onlyoffce port(80) to server, do not worked, but when i open all docker subnet access to my server, it worked.

**Comment by ShockwaveNN** [comment]
I'm not sure, i think it's related to firewall you've using, or docker service itself, I don't think this problem is directly related to our product

**Comment by SizerSong** [comment]
@ShockwaveNN 
thanks again! by the way, Are there any special restrictions on jpg file? when i open a jpg (about 9Mb) in seafile server Integrated with onlyoffice, Popover says "The image could not be loaded", and i check the onlyoffice log, nothing there.

**Comment by ShockwaveNN** [comment]
I think it may be a timout on seafile side or a lot of different situation

The proper way to check it - start integrated example (via 'http://docserverurl/welcome'), check via /example that that image can be inserted

If not - it may be a problem on DocumentServer side, if it can be inserted - problem on DMS/integration side

**Comment by SizerSong** [comment]
Thank you for your detailed and patient answer！

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
