### ISSUE TITLE
Cannot edit document in example page

### ISSUE THREAD

**Issue by schklom** [ONLYOFFICE/Docker-DocumentServer#458]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Creating a new document in the example page ends with

![Screenshot from 2022-07-10 00-09-40](https://user-images.githubusercontent.com/23263086/178124304-546cce1a-758e-4ccc-9d86-d0c35a3e812b.png)

and log
```sh
$ docker logs -f onlyoffice
 * Starting PostgreSQL 12 database server
   ...done.
 * Starting RabbitMQ Messaging Server rabbitmq-server
   ...done.
psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:4: NOTICE:  table "doc_callbacks" does not exist, skipping
psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:9: NOTICE:  function merge_db(pg_catalog.varchar,int2,int8,pg_catalog.timestamp,pg_catalog.varchar,int8,int8) does not exist, skipping
psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:10: NOTICE:  function merge_db(pg_catalog.varchar,int2,int4,pg_catalog.timestamp,pg_catalog.varchar,int4,int4) does not exist, skipping
Starting supervisor: supervisord.
 * Starting periodic command scheduler cron
   ...done.
 * Starting nginx nginx
   ...done.
Generating AllFonts.js, please wait...Done
Generating presentation themes, please wait...Done
ds:docservice: stopped
ds:docservice: started
ds:converter: stopped
ds:converter: started
 * Reloading nginx configuration nginx
   ...done.
==> /var/log/onlyoffice/documentserver/converter/err.log <==

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2022-07-09T22:06:56.896] [WARN] nodeJS - update cluster with 1 workers
[2022-07-09T22:07:02.035] [ERROR] nodeJS - error downloadFile:url=http://10.0.0.206:53148/example/download?fileName=new.docx&useraddress=10.0.0.5;attempt=1;code:EHOSTUNREACH;connect:undefined;(id=10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404420128)
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-07-09T22:07:03.047] [ERROR] nodeJS - error downloadFile:url=http://10.0.0.206:53148/example/download?fileName=new.docx&useraddress=10.0.0.5;attempt=2;code:EHOSTUNREACH;connect:undefined;(id=10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404420128)
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-07-09T22:07:04.050] [ERROR] nodeJS - error downloadFile:url=http://10.0.0.206:53148/example/download?fileName=new.docx&useraddress=10.0.0.5;attempt=3;code:EHOSTUNREACH;connect:undefined;(id=10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404420128)
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

==> /var/log/onlyoffice/documentserver/docservice/err.log <==

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2022-07-09T22:06:31.214] [ERROR] nodeJS - postData error: docId = 10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404389343;url = http://10.0.0.206:53148/example/track?filename=new.docx&useraddress=10.0.0.5;data = {"key":"10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404389343","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}]}
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-07-09T22:06:55.578] [WARN] nodeJS - Express server starting...
[2022-07-09T22:06:55.580] [WARN] nodeJS - Set services.CoAuthoring.token.enable.browser, services.CoAuthoring.token.enable.request.inbox, services.CoAuthoring.token.enable.request.outbox in the Document Server config to prevent an unauthorized access to your documents and the substitution of important parameters in ONLYOFFICE Document Server requests.
[2022-07-09T22:06:55.581] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2022-07-09T22:06:55.608] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 7.1.1. Build: 23
[2022-07-09T22:07:01.996] [ERROR] nodeJS - postData error: docId = 10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404420128;url = http://10.0.0.206:53148/example/track?filename=new.docx&useraddress=10.0.0.5;data = {"key":"10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404420128","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}]}
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

==> /var/log/onlyoffice/documentserver-example/out.log <==

==> /var/log/onlyoffice/documentserver/metrics/err.log <==

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
9 Jul 22:06:07 - [906] reading config file: ./config/config.js
9 Jul 22:06:07 - server is up INFO

==> /var/log/onlyoffice/documentserver/nginx.error.log <==
2022/07/09 22:06:13 [error] 941#941: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.5, server: , request: "GET /example/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "10.0.0.206:53148"
2022/07/09 22:06:13 [error] 941#941: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.5, server: , request: "GET /example/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "10.0.0.206:53148"

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2022-07-09T22:08:04.510] [WARN] nodeJS - error description: docId = 10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404420128 errorId = Other error
[2022-07-09T22:08:14.887] [ERROR] nodeJS - postData error: docId = 10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404420128;url = http://10.0.0.206:53148/example/track?filename=new.docx&useraddress=10.0.0.5;data = {"key":"10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404420128","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}]}
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2022-07-09T22:08:14.897] [ERROR] nodeJS - error downloadFile:url=http://10.0.0.206:53148/example/download?fileName=new.docx&useraddress=10.0.0.5;attempt=1;code:EHOSTUNREACH;connect:undefined;(id=10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404420128)
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-07-09T22:08:15.900] [ERROR] nodeJS - error downloadFile:url=http://10.0.0.206:53148/example/download?fileName=new.docx&useraddress=10.0.0.5;attempt=2;code:EHOSTUNREACH;connect:undefined;(id=10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404420128)
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-07-09T22:08:16.902] [ERROR] nodeJS - error downloadFile:url=http://10.0.0.206:53148/example/download?fileName=new.docx&useraddress=10.0.0.5;attempt=3;code:EHOSTUNREACH;connect:undefined;(id=10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657404420128)
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
client_loop: send disconnect: Broken pipe
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
docker-compose.yaml
```yaml
services:
  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest-arm64
    volumes:
      - ./onlyoffice/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - ./onlyoffice/example:/var/www/onlyoffice/documentserver-example/public/files
      - ./onlyoffice/fonts:/usr/share/fonts
    ports:
      - 53148:80
```

Commands
```sh
$ sudo rm -rf ./onlyoffice/
$ docker compose up -d onlyoffice
$ docker exec onlyoffice sudo supervisorctl start ds:example
```

**What is the expected behavior?**
Documents (and spreadsheets etc) can be edited

**Did this work in previous versions of DocumentServer?**
First attempt

**DocumentServer Docker tag:**
`latest-arm64`

**Host Operating System:**
Ubuntu 20.04

**Comment by ShockwaveNN** [comment]
Juding by your logs it may be netwroking issue

You can try to attach to docker container and try to download file from bash using

```
curl http://10.0.0.206:53148/example/download?fileName=new.docx
```

And if this fail - something wrong with networkin of docker or this may be firewall problem

This is similar to https://github.com/ONLYOFFICE/DocumentServer/issues/1819

But we didn't find that happend wrong

**Comment by schklom** [comment]
From my computer directly (10.0.0.5), I can download the file with
```sh
curl http://10.0.0.206:53148/example/download?fileName=new.docx --output new.docx
```
and `new.docx` is a Word document containing the following
```
Error.
An error occurred while processing your request.
ENOENT: no such file or directory, stat '/var/lib/onlyoffice/documentserver-example/files/10.0.0.206/new.docx'
```

Inside the container
```sh
root@13744b0c61d0:~# ls -lhR /var/lib/onlyoffice/documentserver-example/files
/var/lib/onlyoffice/documentserver-example/files:
total 8.0K
drwxr-xr-x 2 ds ds 4.0K Jul 10 18:54 10.0.0.206
drwxr-xr-x 3 ds ds 4.0K Jul 10 18:52 10.0.0.5

/var/lib/onlyoffice/documentserver-example/files/10.0.0.206:
total 0

/var/lib/onlyoffice/documentserver-example/files/10.0.0.5:
total 12K
-rw-r--r-- 1 ds ds 6.8K Jul 10 18:52 new.docx
drwxr-xr-x 2 ds ds 4.0K Jul 10 18:52 new.docx-history

/var/lib/onlyoffice/documentserver-example/files/10.0.0.5/new.docx-history:
total 4.0K
-rw-r--r-- 1 ds ds 36 Jul 10 18:52 new.docx.txt
```

The directory under `10.0.0.206` is empty, this is why it cannot find a Word document there.

I can still see the error logs
```sh
==> /var/log/onlyoffice/documentserver/converter/out.log <==
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-07-10T18:52:48.172] [ERROR] nodeJS - error downloadFile:url=http://10.0.0.206:53148/example/download?fileName=new.docx&useraddress=10.0.0.5;attempt=1;code:EHOSTUNREACH;connect:undefined;(id=10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479167038)
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-07-10T18:52:49.174] [ERROR] nodeJS - error downloadFile:url=http://10.0.0.206:53148/example/download?fileName=new.docx&useraddress=10.0.0.5;attempt=2;code:EHOSTUNREACH;connect:undefined;(id=10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479167038)
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-07-10T18:52:50.177] [ERROR] nodeJS - error downloadFile:url=http://10.0.0.206:53148/example/download?fileName=new.docx&useraddress=10.0.0.5;attempt=3;code:EHOSTUNREACH;connect:undefined;(id=10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479167038)
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

==> /var/log/onlyoffice/documentserver/docservice/err.log <==

==> /var/log/onlyoffice/documentserver/docservice/out.log <==
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-07-10T18:52:41.541] [ERROR] nodeJS - postData error: docId = 10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479150934;url = http://10.0.0.206:53148/example/track?filename=new.docx&useraddress=10.0.0.5;data = {"key":"10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479150934","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}]}
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-07-10T18:52:43.423] [ERROR] nodeJS - postData error: docId = 10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479150934;url = http://10.0.0.206:53148/example/track?filename=new.docx&useraddress=10.0.0.5;data = {"key":"10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479150934","status":4,"actions":[{"type":0,"userid":"uid-1"}]}
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-07-10T18:52:48.165] [ERROR] nodeJS - postData error: docId = 10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479167038;url = http://10.0.0.206:53148/example/track?filename=new.docx&useraddress=10.0.0.5;data = {"key":"10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479167038","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}]}
Error: connect EHOSTUNREACH 10.0.0.206:53148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

==> /var/log/onlyoffice/documentserver-example/out.log <==

==> /var/log/onlyoffice/documentserver/metrics/err.log <==

==> /var/log/onlyoffice/documentserver/metrics/out.log <==
10 Jul 18:51:42 - [906] reading config file: ./config/config.js
10 Jul 18:51:42 - server is up INFO

==> /var/log/onlyoffice/documentserver/nginx.error.log <==
2022/07/10 18:52:06 [error] 940#940: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.5, server: , request: "GET /example/editor?fileName=new.docx HTTP/1.1", upstream: "http://127.0.0.1:3000/editor?fileName=new.docx", host: "10.0.0.206:53148", referrer: "http://10.0.0.206:53148/example/"
2022/07/10 18:52:06 [error] 940#940: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.5, server: , request: "GET /example/editor?fileName=new.docx HTTP/1.1", upstream: "http://127.0.0.1:3000/editor?fileName=new.docx", host: "10.0.0.206:53148", referrer: "http://10.0.0.206:53148/example/"
2022/07/10 18:52:31 [error] 940#940: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.5, server: , request: "GET /7.1.1-23/doc/10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479150934/c/info?t=1657479151693 HTTP/1.1", upstream: "http://127.0.0.1:8000/doc/10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479150934/c/info", host: "10.0.0.206:53148", referrer: "http://10.0.0.206:53148/7.1.1-23/web-apps/apps/documenteditor/main/index.html?_dc=7.1.1-23&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&parentOrigin=http://10.0.0.206:53148"
2022/07/10 18:52:31 [error] 940#940: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.5, server: , request: "GET /7.1.1-23/doc/10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479150934/c/info?t=1657479151693 HTTP/1.1", upstream: "http://127.0.0.1:8000/doc/10.0.0.5http___10.0.0.206_53148_example_files_10.0.0.5_new.docx1657479150934/c/info", host: "10.0.0.206:53148", referrer: "http://10.0.0.206:53148/7.1.1-23/web-apps/apps/documenteditor/main/index.html?_dc=7.1.1-23&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor&parentOrigin=http://10.0.0.206:53148"
```

I tried the [docker command on the main page of this repo](https://github.com/ONLYOFFICE/Docker-DocumentServer#running-docker-image)
```sh
sudo docker run -i -t -d -p 80:80 onlyoffice/documentserver
```
but it leads to the same issue.

Is there anything else I can try?

**Comment by schklom** [comment]
I tried to download the file from outside the network via a reverse-proxy, and `new.docx` is instead a blank Word file, nothing inside.

I'm not sure if it helps though :P

**Comment by ShockwaveNN** [comment]
> the network via a reverse-proxy,

Do you use some kind of proxy\reverse proxy in this network?

**Comment by schklom** [comment]
The issue and my first reply to you are done without a reverse-proxy.
My 3rd reply is an attempt with one.

**Comment by ShockwaveNN** [comment]
Do you got any firewalls? I'm almost out of ideas

I think you should setup same server on some cloud host provider, I'm almost 100% sure it will work without problem on real IP and after that compare that is different on your network

**Comment by schklom** [comment]
Per your suggestion, I tried with a cloud host provider without a reverse-proxy, and it works!
With Traefik, I am able to make it work with the middleware
```yaml
http:
  middlewares:
    secure-headers:
      headers:
        customrequestheaders:
          X-Forwarded-Proto: https
```
https://github.com/ONLYOFFICE/document-server-proxy should really be updated :P
