### ISSUE TITLE
ConvertService.ashx returns ERROR 504 status while converting .doc files

### ISSUE THREAD

**Issue by DmitriyReztsov** [ONLYOFFICE/Docker-DocumentServer#682]
**Do you want to request a *feature* or report a *bug*?**

**BUG**

**What is the current behavior?**

**ConvertService.ashx doesn't work properly. It works with .docx, but doesn't with .doc**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Go to documentserver/welcome -> documentserver/example/ and try to upload file with .doc extension. I've got 
![изображение](https://github.com/ONLYOFFICE/Docker-DocumentServer/assets/68148319/06f5cfd4-7a4c-4d0c-ada6-6c5a9d20b764)
and in log:
```
==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2023-11-21T13:53:13.130] [ERROR] [localhost] [conv_http___localhost_1080_example_download_fileName=PO08712-043_Texas_Trailer_Supply_1_.doc_useraddress=172.23.0.11700574792023_docx] [userId] nodeJS - error downloadFile:url=http://localhost:1080/example/download?fileName=PO08712-043_Texas_Trailer_Supply(1).doc&useraddress=172.23.0.1;attempt=1;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:1080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2023-11-21T13:53:14.136] [ERROR] [localhost] [conv_http___localhost_1080_example_download_fileName=PO08712-043_Texas_Trailer_Supply_1_.doc_useraddress=172.23.0.11700574792023_docx] [userId] nodeJS - error downloadFile:url=http://localhost:1080/example/download?fileName=PO08712-043_Texas_Trailer_Supply(1).doc&useraddress=172.23.0.1;attempt=2;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:1080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2023-11-21T13:53:15.141] [ERROR] [localhost] [conv_http___localhost_1080_example_download_fileName=PO08712-043_Texas_Trailer_Supply_1_.doc_useraddress=172.23.0.11700574792023_docx] [userId] nodeJS - error downloadFile:url=http://localhost:1080/example/download?fileName=PO08712-043_Texas_Trailer_Supply(1).doc&useraddress=172.23.0.1;attempt=3;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:1080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
```
meanwhile .docx uploaded as it should be

**What is the expected behavior?**

to upload .doc properly

**Did this work in previous versions of DocumentServer?**

users didn't report about such issues before

**DocumentServer Docker tag:**

onlyoffice/documentserver-de:7.2.2

**Host Operating System:**

Ubuntu 22.04.3

**Comment by igwyd** [comment]
Hello @DmitriyReztsov, thank you for the report. This bug in the test example, not in the ConvertService, we know about it, we have ticket #47760. The ConvertService works with any integrations at the time and with test example if you do not change the port.
